# Generated by Django 4.1.3 on 2022-11-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='field_legth',
            field=models.IntegerField(default=90),
        ),
    ]
