# Generated by Django 4.1.3 on 2022-11-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_matches_field_legth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='field_legth',
            new_name='field_length',
        ),
    ]
