# Generated by Django 4.1.3 on 2022-12-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-tournament', '-date'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
    ]
