# Generated by Django 4.1.3 on 2022-11-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('matches', '0004_matches_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='tournaments.tournament', verbose_name='seasons'),
            preserve_default=False,
        ),
    ]
