# Generated by Django 4.1.3 on 2022-12-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_options_remove_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
