# Generated by Django 4.1.3 on 2022-12-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-tournament'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
    ]
