# Generated by Django 4.1.3 on 2022-11-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matches_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='season',
        ),
    ]
