# Generated by Django 4.1.3 on 2022-12-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0005_remove_season_description_season_current_season'),
        ('matches', '0012_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.season'),
        ),
    ]
