# Generated by Django 4.1.3 on 2022-12-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_match_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['season', '-date'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='is_playoff',
            field=models.BooleanField(default=False, verbose_name='Is it playoff'),
        ),
    ]
