# Generated by Django 4.1.3 on 2022-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_alter_match_match type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Match Type',
            field=models.BooleanField(default=False, verbose_name='Playoff Match'),
        ),
    ]
