# Generated by Django 4.1.3 on 2022-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_statsmatchonline_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsmatchonline',
            name='date',
        ),
        migrations.AddField(
            model_name='statsmatchonline',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
