# Generated by Django 4.1.3 on 2022-12-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_alter_match_match type'),
        ('stats', '0003_remove_statsmatchonline_date_statsmatchonline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsmatchonline',
            name='name',
        ),
        migrations.AddField(
            model_name='statsmatchonline',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statsmatchonline',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statsmatchonline',
            name='score_team_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statsmatchonline',
            name='score_team_b',
            field=models.IntegerField(default=0),
        ),
    ]
