# Generated by Django 4.1.3 on 2022-12-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_statsmatchonline_name_statsmatchonline_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsmatchonline',
            name='date',
        ),
    ]
