# Generated by Django 4.1.3 on 2022-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_year'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='season',
        ),
        migrations.AddField(
            model_name='tournament',
            name='seasons_all',
            field=models.ManyToManyField(to='seasons.season'),
        ),
    ]
