# Generated by Django 4.1.3 on 2022-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_year'),
        ('tournaments', '0002_remove_tournament_season_tournament_seasons_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_season_set',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='current_season_set', to='seasons.season'),
            preserve_default=False,
        ),
    ]
