# Generated by Django 4.1.3 on 2022-12-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_year'),
        ('tournaments', '0003_tournament_current_season_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='current_season_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_season_set', to='seasons.season'),
        ),
    ]
