# Generated by Django 4.1.3 on 2022-12-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_year'),
        ('tournaments', '0004_alter_tournament_current_season_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='current_season_set',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='seasons_all',
        ),
        migrations.AddField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seasons.season'),
        ),
    ]
