# Generated by Django 4.1.3 on 2022-12-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_tournament_current_season_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-season'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournament'},
        ),
    ]
