# Generated by Django 4.1.3 on 2022-12-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournament_options_remove_tournament_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-name'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournament'},
        ),
    ]
