# Generated by Django 4.1.3 on 2022-12-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
