# Generated by Django 4.1.3 on 2022-12-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_alter_season_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='description',
        ),
        migrations.AddField(
            model_name='season',
            name='current_season',
            field=models.BooleanField(default=False),
        ),
    ]
