# Generated by Django 4.1.3 on 2022-12-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0007_alter_season_season type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='Season Type',
            new_name='current_season',
        ),
    ]
